### ISSUE TITLE
Wrong running the BuildStandardTypes.bat

### ISSUE THREAD

**Issue by 0DennisLee0** [OPCFoundation/UA-ModelCompiler#46]
When I run this batch file, there will always be a hint that the 
`
The SymbolicId is already used by another node: CurrencyUnitType.
`
I make sure I download it alright.

**Comment by 0DennisLee0** [comment]
And here is a exception 
`
Could not load resource 'Opc.Ua.ModelCompiler.Design.BuiltInTypes.xml'
` as well. And cannot generate codes

**Comment by zanseb** [comment]
I also get the exception `Could not load resource 'Opc.Ua.ModelCompiler.Design.BuiltInTypes.xml'` when trying to publish a model. Current commit is cf99bfa3.

**Comment by 0DennisLee0** [comment]
> I also get the exception `Could not load resource 'Opc.Ua.ModelCompiler.Design.BuiltInTypes.xml'` when trying to publish a model. Current commit is [cf99bfa](https://github.com/OPCFoundation/UA-ModelCompiler/commit/cf99bfa35a5b0d72133e581272d20ff77999e7ef).
I have fixed it but the method is a little bit complex.I will answer you tomorrow

**Comment by 0DennisLee0** [comment]
> I also get the exception `Could not load resource 'Opc.Ua.ModelCompiler.Design.BuiltInTypes.xml'` when trying to publish a model. Current commit is [cf99bfa](https://github.com/OPCFoundation/UA-ModelCompiler/commit/cf99bfa35a5b0d72133e581272d20ff77999e7ef).

You can turn to the branch "v1.04" and copy .\ModelCompiler\Design and rename the copy Design file as Design.v104. I have succeeded by doing this

**Comment by MPJansen** [comment]
It seems as if the maintainers forgot to update some paths.
If I change the following line:

`            EmbeddedResourcePath = "Opc.Ua.ModelCompiler.Design";
`
to
`            EmbeddedResourcePath = "Opc.Ua.ModelCompiler.Design.v104";
`

The current master starts finding the correct paths again. Obviously this isnt a fix..

**Comment by opcfoundation-org** [comment]
Should be fixed now.

**Comment by benkinooby** [comment]
No, it is not fixed. Please reopen.

From what I understand, using flag `-version v104` for executing Opc.Ua.ModelCompiler.exe should be equivalent to the fix presented in this issue here https://github.com/OPCFoundation/UA-ModelCompiler/issues/46#issuecomment-603875272

But neiter of both solutions leads to a successful compilation of the model. Details here:
https://opcua.rocks/step-7-compile-the-modeldesign-file-with-ua-modelcompiler/#comment-809

Question: What is the difference between using '-version v104' and not using that flag at all?

Kind regards & thanks in advance

**Comment by benkinooby** [comment]
Ok, it seems fixed and I was mistaken. Apologies.

I will leave https://github.com/OPCFoundation/UA-ModelCompiler/issues/46#issuecomment-695184092 to serve as context for the following solution.

Use `-version v104` when runnging `.\Opc.Ua.ModelCompiler.exe`

Calling
`PS C:\UA-ModelCompiler\Bin\Release> .\Opc.Ua.ModelCompiler.exe -d2 C:\opcua-modeling-tutorial\FooFltModel.xml -cg C:\opcua-modeling-tutorial\FooFltModel.csv -o2 C:\opcua-modeling-tutorial\FooFltModel -console -version v104`

will still fail with error

 `Could not find a part of the path ‘C:\opcua-modeling-tutorial\FooFltModel\FooFlt.Constants.cs’.`

Manually create `C:\opcua-modeling-tutorial\FooFltModel` in already existing folder `C:\opcua-modeling-tutorial`.

Now, `.\Opc.Ua.ModelCompiler.exe -d2 C:\opcua-modeling-tutorial\FooFltModel.xml -cg C:\opcua-modeling-tutorial\FooFltModel.csv -o2 C:\opcua-modeling-tutorial\FooFltModel -console -version v104` will exit successfully.

**Comment by opcfoundation-org** [comment]
There was an issue which was fixed now.

**Comment by benkinooby** [comment]
Thank you very much for your effort!

> There was an issue which was fixed now.
I know I am in no position to ask anything of you, but a reference to the fix and more verbose git commit messages would help me (and others) a long way with using the software and more importantly, diagnosing and reporting issues. Please receive that note in the most amicable way possible.
