### ISSUE TITLE
Effective licensing of the repository outcomes - add info to README.md

### ISSUE THREAD

**Issue by mpostol** [OPCFoundation/UA-ModelCompiler#74]
This repository is MIT licensed, but from .gitmodules we can learn

```txt
[submodule "Stack"]
		path = Stack
		url = https://github.com/OPCFoundation/UA-.NETStandard.git
```

As far as I know, the `OPCFoundation/UA-.NETStandard` has an incompatible license but the code here depends on it.  My concern is what is an effective license for the deliverables created based on this repository. 

It is a blocker for mpostol/ASMD#198

**Comment by opcfoundation-org** [comment]
Will raise this with the TCB.

**Comment by opcfoundation-org** [comment]
The next public release of the ModeCompiler will use the .NETStandard NuGet packages.
This should eliminate any concern about licensing.

**Comment by opcfoundation-org** [comment]
Need to wait for the pull request to be accepted by the .NETStandard stack team before the MC can be linked to the NuGet packages.

**Comment by opcfoundation-org** [comment]
The codebase now uses the NuGet packages. You licensing issues should be resolved.

**Comment by mpostol** [comment]
@opcfoundation-org  - thanks, but my point is that unfortunately, the problem persists.  It is not important if we referring to external source code or external packages. In both cases, they are licensed separately. My point is that the license of this repository (MIT) is not compliant with the license of the nugget packages: 

[OPCFoundation.NetStandard.Opc.Ua](https://www.nuget.org/packages/OPCFoundation.NetStandard.Opc.Ua.Core/1.4.365.48/License). 

For me, the MIT license is more permissive than the custom licenses attached to the packages.

I am not a lawyer and like most of the users, I don't have the background knowledge to resolve the impact of the NuGet package's license on the base code dependent on these packages.  Therefore, I will appreciate a clear statement in the README.md covering the list of dependencies and final limitations the users must consider using/distributing the source code and deliverables.

Let me stress. My code depends on this repository outcome. Previously the source code was here. Now partially it is removed and the rest depends on the external deliverables licensed separately. In other words, previously we had one MIT license, now we have many that must be considered as one whole.

**Comment by opcfoundation-org** [comment]
Anyone can use the pre-built binaries without imposing burdens on s/w built against those libraries.
Building against the source comes with GPL or RCL burdens.

This should be sufficient for anyone who wants to modify and redistribute the ModelCompiler code base.

**Comment by mpostol** [comment]
Not sure how you have derived the sentence: `Building against the source comes with GPL or RCL burdens.` How it applies to the problem I have reported?

**Comment by opcfoundation-org** [comment]
I feel I did address your concerns.
You can modify and distribute the ModelCompiler code without restriction as long as you use the pre-built binaries.
That statement can be confirmed by reading the NuGet package license agreement.

It is no different from building .NET applications that are subject to [Microsoft's terms for the .NET Framework.](https://dotnet.microsoft.com/en/dotnet_library_license.htm)
i.e. MS did not make the NET Framework MIT but you presumably have no issue using the NET binaries.
Why are OPC-F supplied binaries an issue when NET binaries are not?

**Comment by opcfoundation-org** [comment]
I feel I did address your concerns.
You can modify and distribute the ModelCompiler code without restriction as long as you use the pre-built binaries.
That statement can be confirmed by reading the NuGet package license agreement.

Can you please explain what more you need other than a note in the readme?

**Comment by mpostol** [comment]
@opcfoundation-org I really appreciate your explanation. Many thanks for your engagement. The only goal I have is to confirm that replacing the code with the external NuGet package(s) changes the licensing policy of the repository outcome as a side effect. It is a new situation that must be signaled to all users. I know that I can read the license of the external packages, but first I must be aware that there is a fundamental change that has an impact on the licensing policy (that I must read something). My point is that it should be manifested as a warning in the README.md file. 

I am not in charge to suggest the content of the message. As I said previously it should provide information about dependencies that has an impact on the outcome license and describe the limitations that must be also added to the derived code/products. 
I know that your comments are on behalf of the OPC Foundation organization and I am not questioning your rights to provide explanations related to license regulations but we must be aware that they have legal effects. This discussion will disappear after closing the issue at the end of the day but the legal effects will be valid also in the future.

Let me stress I am not expecting anything more than just a note (warning) in the readme stating that starting from the Version .....  I am also expecting that the note will be issued on behalf of (will be approved by) the organization authorities.

**Comment by mpostol** [comment]
6 day ego (commit 6857db62e9c723def61108ce464fb04a89631e7f) the README changed the description related to the code license. From the added text we can read:

```txt

## License Model ##

The ModelCompiler code is MIT license, however, it links to the UA-.NETStandard NuGet packages which is covered under the OPC Foundation Redistributables licence. If a user chooses the version that links directly to the  UA-.NETStandard submodule then the license the UA-.NETStandard dual license applies.

```
It is not any news but now it clearly states that the code dependencies have an incompatible license.
